### ISSUE TITLE
Cant run my typescript file

### ISSUE THREAD

**Issue by Phyroks** [Tolfix/pterodactyl-eggs#1]
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/container/index.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

**Comment by Tolfx** [comment]
Hi!
Are you using the correct image? Also node can't directly run .ts you need to compile them.

**Comment by Phyroks** [comment]
How do I compile it ?

**Comment by Tolfx** [comment]
> How do I compile it ?

Well it does compile with `tsc`, but in your tsconfig.json you need to specific where the outDir will be. Then run your index where it got compiled.

**Comment by Phyroks** [comment]
I don't have a ts-config

**Comment by Tolfx** [comment]
How did you run it before? With `ts-node`?
